### ISSUE TITLE
Docs and default format for dates do not match

### ISSUE THREAD

**Issue by jdevera** [dvargas92495/roamjs-google-calendar#4]
Docs say:
> By default, Format will be `{summary} ({start:hh:mm a} - {end:hh:mm a}) - [Meet|Zoom]{link}`

However, when running some tests, I get:

`Meditation retreat (9:00:00 AM - 9:30:00 AM) - [Meet](https://meet-link)`

Is this a doc problem or a code problem?

**Comment by dvargas92495** [comment]
where does that not match?

**Comment by jdevera** [comment]
Dates are coming out as `h:mm:ss a`  (including seconds and no leading zero), contrary to what the docs day. Code inspection shows that dates are formatted with `toLocaleTimeString()` in the absence of an explicit format, which means the results will vary depending on the user's locale, rather than or using a specific format string.

I'm still unsure of the way to go is to adapt the docs to describe this or to change the code to have the documented default format when one is not present in the format string.

**Comment by dvargas92495** [comment]
oh I see now. I think I would prefer the latter and not use `toLocaleTimeString`

**Comment by jdevera** [comment]
Will give it a go, thanks!
