### ISSUE TITLE
Attendee format NAME placeholder replaced only once

### ISSUE THREAD

**Issue by jdevera** [dvargas92495/roamjs-google-calendar#5]
if I use `{attendees:[NAME](https://example.com/NAME)}` the `NAME` placeholder gets replaced only once. I tried using `.replaceAll` instead of `.replace` but I met a JS version hell that I could not navigate 😅.

How would you go about this? If you give me some pointers I could send a PR 👼

**Comment by dvargas92495** [comment]
we just need to replace `"NAME"` here with `/NAME/g` (global regex)

https://github.com/dvargas92495/roamjs-google-calendar/blob/main/src/index.ts#L77
